Use sqlclient;
CREATE TABLE Accounts
(
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (username)
);
CREATE TABLE Admin
(
  Aid INT AUTO_INCREMENT  NOT NULL,
  Name VARCHAR(255) NOT NULL,
  DOB DATE NOT NULL,
  username VARCHAR(255) NOT NULL,
  PRIMARY KEY (Aid),
  FOREIGN KEY (username) REFERENCES Accounts(username)

);
CREATE TABLE Posts
(
  Pid INT AUTO_INCREMENT NOT NULL,
  PostTime DATETIME NOT NULL,
  TimeEVENT DATETIME NOT NULL,
  Title VARCHAR(255) NOT NULL,
  _Event VARCHAR(255) NOT NULL,
  Content TEXT NOT NULL,
  Image VARCHAR(255) NOT NULL,
  Aid INT  NOT NULL,
  PRIMARY KEY (Pid),
  FOREIGN KEY (Aid) REFERENCES Admin(Aid)
);

CREATE TABLE Finder
(
  Finder_key INT NOT NULL,
  Pid INT NOT NULL,
  PRIMARY KEY (Finder_key),
  FOREIGN KEY (Pid) REFERENCES Posts(Pid)
);

CREATE TABLE Student
(
  Sid INT NOT NULL,
  SName VARCHAR(255) NOT NULL,
  DOB DATE NOT NULL,
  Class VARCHAR(50) NOT NULL,
  Major VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  Aid INT NOT NULL,
  PRIMARY KEY (Sid),
  FOREIGN KEY (username) REFERENCES Accounts(username),
  FOREIGN KEY (Aid) REFERENCES Admin(Aid)
);
CREATE TABLE Feedbacks
(
  F_ID INT AUTO_INCREMENT  NOT NULL,
  UName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  FbContent TEXT NOT NULL,
  Sid INT NULL,
  Aid INT NULL,
  PRIMARY KEY (F_ID),
  FOREIGN KEY (Sid) REFERENCES Student(Sid),
  FOREIGN KEY (Aid) REFERENCES Admin(Aid)
);

